import React, { useState, useEffect } from 'react';
import { Loader2, X, Database, Server as ServerIcon, Globe, Box, ShieldCheck, Cpu } from 'lucide-react';
import type { Server } from '../services/serversService';
import { deleteServer } from '../services/serversService';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

function cn(...inputs: ClassValue[]) {
    return twMerge(clsx(inputs));
}

interface ServerModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSave: (server: Partial<Server>) => Promise<void>;
    initialData?: Server | null;
}

// Preset configurations
const SERVER_PRESETS = [
    { id: 'fms', label: 'Servidor FMS', type: 'Servidor FMS', os: 'Linux', port: '22', protocol: 'SSH', icon: ServerIcon, color: 'text-orange-500 bg-orange-500/10 border-orange-200' },
    { id: 'base', label: 'Estacion Base', type: 'Estacion Base', os: 'Linux', port: '22', protocol: 'SSH', icon: Globe, color: 'text-blue-500 bg-blue-500/10 border-blue-200' },
    { id: 'tunel', label: 'Tunel', type: 'Tunel', os: 'Linux', port: '8080', protocol: 'HTTP', icon: Box, color: 'text-purple-500 bg-purple-500/10 border-purple-200' },
    { id: 'pivote', label: 'Pivote', type: 'Pivote', os: 'Linux', port: '22', protocol: 'SSH', icon: ShieldCheck, color: 'text-indigo-500 bg-indigo-500/10 border-indigo-200' },
    { id: 'cas', label: 'Servidor CAS', type: 'Servidor CAS', os: 'Windows', port: '3389', protocol: 'RDP', icon: Database, color: 'text-emerald-500 bg-emerald-500/10 border-emerald-200' },
    { id: 'sql', label: 'SQL Server', type: 'Servidor SQL Server', os: 'Windows', port: '1433', protocol: 'TDS', icon: Database, color: 'text-red-500 bg-red-500/10 border-red-200' },
    { id: 'jview', label: 'Servidor Jview', type: 'Servidor Jview', os: 'Linux', port: '80', protocol: 'HTTP', icon: Globe, color: 'text-cyan-500 bg-cyan-500/10 border-cyan-200' },
];

const ServerModal = ({ isOpen, onClose, onSave, initialData }: ServerModalProps) => {
    // Core Fields
    const [name, setName] = useState('');
    const [ip, setIp] = useState('');
    const [os, setOs] = useState('Linux');
    const [type, setType] = useState('Generic');
    const [description, setDescription] = useState('');
    const [notes, setNotes] = useState('');

    // Auth Fields
    const [sshUser, setSshUser] = useState('');
    const [sshPassword, setSshPassword] = useState('');
    const [dbUser, setDbUser] = useState('');
    const [dbPassword, setDbPassword] = useState('');

    // Extra Technical Fields (Phase 8.2)
    const [port, setPort] = useState('');
    const [protocol, setProtocol] = useState('');
    const [dbEngine, setDbEngine] = useState('');
    const [dbName, setDbName] = useState('');

    const [loading, setLoading] = useState(false);

    useEffect(() => {
        if (initialData) {
            setName(initialData.name);
            setIp(initialData.ip_address);
            setOs(initialData.os);
            setType(initialData.server_type);
            setDescription((initialData.description || '').replace(/\\n/g, '\n'));
            setNotes((initialData.notes || '').replace(/\\n/g, '\n'));
            setSshUser(initialData.ssh_user || '');
            setSshPassword(initialData.ssh_password || '');
            setDbUser(initialData.db_user || '');
            setDbPassword(initialData.db_password || '');
            setPort(initialData.port || '');
            setProtocol(initialData.protocol || '');
            setDbEngine(initialData.db_engine || '');
            setDbName(initialData.db_name || '');
        } else {
            resetForm();
        }
    }, [initialData, isOpen]);

    const resetForm = () => {
        setName('');
        setIp('');
        setOs('Linux');
        setType('Generic');
        setDescription('');
        setNotes('');
        setSshUser('');
        setSshPassword('');
        setDbUser('');
        setDbPassword('');
        setPort('');
        setProtocol('');
        setDbEngine('');
        setDbName('');
    };

    const applyPreset = (preset: typeof SERVER_PRESETS[0]) => {
        setType(preset.type);
        setOs(preset.os);
        setPort(preset.port);
        setProtocol(preset.protocol);

        // Update name if it's empty OR if it looks like an auto-generated name from another preset
        const isAutoGenerated = name === '' || SERVER_PRESETS.some(p => name === `Servidor ${p.label}`);
        if (isAutoGenerated) {
            setName(`Servidor ${preset.label}`);
        }
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);
        try {
            console.log("Submitting server data:", { name, ip }); // Debug

            await onSave({
                id: initialData?.id,
                name,
                ip_address: ip,
                os,
                server_type: type,
                description,
                notes,
                ssh_user: sshUser,
                ssh_password: sshPassword,
                db_user: dbUser,
                db_password: dbPassword,
                port,
                protocol,
                db_engine: dbEngine,
                db_name: dbName
            });
            onClose();
        } catch (error: any) {
            console.error("Failed to save server", error);
            // Alert the user with the specific error message if available
            const msg = error.response?.data?.message || error.message || "Error desconocido al guardar";
            alert(`Error al guardar: ${msg}`);
        } finally {
            setLoading(false);
        }
    };

    const handleDelete = async () => {
        if (!initialData?.id) return;
        if (!confirm('¿Estás seguro de que quieres eliminar este servidor? Se mantendrá en el historial pero no estará visible.')) return;

        setLoading(true);
        try {
            await deleteServer(initialData.id);
            onClose();
            window.location.reload();
        } catch (error) {
            console.error("Failed to delete", error);
            alert("Error al eliminar servidor");
        } finally {
            setLoading(false);
        }
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-background/80 backdrop-blur-sm animate-in fade-in duration-200">
            <div className="bg-card rounded-2xl border border-border w-full max-w-4xl shadow-2xl relative max-h-[90vh] flex flex-col">
                <div className="flex items-center justify-between p-6 border-b border-border shrink-0">
                    <div className="flex items-center gap-3">
                        <div className="p-2 bg-primary/10 rounded-lg">
                            <Cpu className="w-6 h-6 text-primary" />
                        </div>
                        <div>
                            <h2 className="text-xl font-bold text-foreground">
                                {initialData ? 'Editar Servidor' : 'Agregar Nuevo Sistema'}
                            </h2>
                            <p className="text-sm text-muted-foreground">
                                {initialData ? 'Modifica los detalles del servidor.' : 'Selecciona un preset o ingresa los datos manualmente.'}
                            </p>
                        </div>
                    </div>
                    <button onClick={onClose} className="text-muted-foreground hover:text-foreground transition-colors p-2 hover:bg-muted rounded-full">
                        <X className="w-6 h-6" />
                    </button>
                </div>

                <div className="overflow-y-auto p-6 space-y-8 custom-scrollbar">

                    {/* Presets Section - Only Show on Create */}
                    {!initialData && (
                        <div className="space-y-3">
                            <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Presets Rápidos (Productos)</label>
                            <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
                                {SERVER_PRESETS.map((preset) => (
                                    <button
                                        key={preset.id}
                                        type="button"
                                        onClick={() => applyPreset(preset)}
                                        className={cn(
                                            "flex flex-col items-center justify-center gap-2 p-3 rounded-xl border transition-all duration-200 hover:shadow-md",
                                            type === preset.type
                                                ? cn(preset.color, "ring-2 ring-offset-1 ring-primary border-transparent bg-opacity-20")
                                                : "bg-card border-border hover:border-primary/50 text-muted-foreground hover:bg-muted/50"
                                        )}
                                    >
                                        <preset.icon className="w-6 h-6" />
                                        <span className="text-xs font-medium">{preset.label}</span>
                                    </button>
                                ))}
                            </div>
                        </div>
                    )}

                    <form id="server-form" onSubmit={handleSubmit} className="space-y-6">
                        {/* Main Info */}
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
                            <div className="lg:col-span-1">
                                <label className="block text-sm font-medium text-foreground mb-1.5">Nombre del Servidor</label>
                                <input
                                    type="text"
                                    value={name}
                                    onChange={(e) => setName(e.target.value)}
                                    placeholder="Ej: FMS Principal"
                                    className="w-full px-4 py-2 bg-muted/30 border border-input rounded-xl focus:ring-2 focus:ring-primary outline-none text-foreground transition-all"
                                    required
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-foreground mb-1.5">Dirección IP</label>
                                <input
                                    type="text"
                                    value={ip}
                                    onChange={(e) => setIp(e.target.value)}
                                    placeholder="10.10.x.x"
                                    className="w-full px-4 py-2 bg-muted/30 border border-input rounded-xl focus:ring-2 focus:ring-primary outline-none text-foreground transition-all"
                                    required
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-foreground mb-1.5">Tipo (Manual)</label>
                                <input
                                    type="text"
                                    value={type}
                                    onChange={(e) => setType(e.target.value)}
                                    list="server-types"
                                    placeholder="Escribe o selecciona..."
                                    className="w-full px-4 py-2 bg-muted/30 border border-input rounded-xl focus:ring-2 focus:ring-primary outline-none text-foreground transition-all"
                                />
                                <datalist id="server-types">
                                    <option value="Servidor FMS" />
                                    <option value="Estacion Base" />
                                    <option value="Tunel" />
                                    <option value="Pivote" />
                                    <option value="Servidor CAS" />
                                    <option value="Servidor SQL Server" />
                                    <option value="Servidor Jview" />
                                </datalist>
                            </div>
                        </div>

                        {/* Details Row */}
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-5">
                            <div>
                                <label className="block text-sm font-medium text-foreground mb-1.5">OS</label>
                                <select
                                    value={os}
                                    onChange={(e) => setOs(e.target.value)}
                                    className="w-full px-4 py-2 bg-muted/30 border border-input rounded-xl focus:ring-2 focus:ring-primary outline-none text-foreground appearance-none transition-all"
                                >
                                    <option>Linux</option>
                                    <option>Windows</option>
                                    <option>Other</option>
                                </select>
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-foreground mb-1.5">Puerto</label>
                                <input
                                    type="text"
                                    value={port}
                                    onChange={(e) => setPort(e.target.value)}
                                    placeholder="22"
                                    className="w-full px-4 py-2 bg-muted/30 border border-input rounded-xl focus:ring-2 focus:ring-primary outline-none text-foreground transition-all"
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-foreground mb-1.5">Protocolo</label>
                                <input
                                    type="text"
                                    value={protocol}
                                    onChange={(e) => setProtocol(e.target.value)}
                                    placeholder="SSH"
                                    className="w-full px-4 py-2 bg-muted/30 border border-input rounded-xl focus:ring-2 focus:ring-primary outline-none text-foreground transition-all"
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-foreground mb-1.5">Motor DB</label>
                                <input
                                    type="text"
                                    value={dbEngine}
                                    onChange={(e) => setDbEngine(e.target.value)}
                                    placeholder="PostgreSQL"
                                    className="w-full px-4 py-2 bg-muted/30 border border-input rounded-xl focus:ring-2 focus:ring-primary outline-none text-foreground transition-all"
                                />
                            </div>
                        </div>

                        {/* Auth Section Box */}
                        <div className="bg-muted/30 border border-border rounded-xl p-5 space-y-4">
                            <div className="flex items-center gap-2 mb-2">
                                <ShieldCheck className="w-4 h-4 text-primary" />
                                <h3 className="text-sm font-semibold text-foreground">Credenciales de Acceso</h3>
                            </div>

                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                {/* SSH/System Auth */}
                                <div className="space-y-3">
                                    <p className="text-xs font-medium text-muted-foreground uppercase">Sistema / SSH</p>
                                    <div className="grid grid-cols-2 gap-3">
                                        <div>
                                            <label className="block text-xs text-muted-foreground mb-1">Usuario</label>
                                            <input
                                                type="text"
                                                value={sshUser}
                                                onChange={(e) => setSshUser(e.target.value)}
                                                className="w-full px-3 py-1.5 bg-background border border-input rounded-lg focus:ring-1 focus:ring-primary outline-none text-sm"
                                                placeholder="jigsaw"
                                            />
                                        </div>
                                        <div>
                                            <label className="block text-xs text-muted-foreground mb-1">Password</label>
                                            <input
                                                type="text"
                                                value={sshPassword}
                                                onChange={(e) => setSshPassword(e.target.value)}
                                                className="w-full px-3 py-1.5 bg-background border border-input rounded-lg focus:ring-1 focus:ring-primary outline-none text-foreground text-sm font-mono"
                                                placeholder="••••••"
                                            />
                                        </div>
                                    </div>
                                </div>

                                {/* DB Auth */}
                                <div className="space-y-3">
                                    <p className="text-xs font-medium text-muted-foreground uppercase">Base de Datos</p>
                                    <div className="grid grid-cols-2 gap-3">
                                        <div className="col-span-2">
                                            <label className="block text-xs text-muted-foreground mb-1">Nombre Base de Datos</label>
                                            <input
                                                type="text"
                                                value={dbName}
                                                onChange={(e) => setDbName(e.target.value)}
                                                className="w-full px-3 py-1.5 bg-background border border-input rounded-lg focus:ring-1 focus:ring-primary outline-none text-sm"
                                                placeholder="Nombre BD (opcional)"
                                            />
                                        </div>
                                        <div>
                                            <label className="block text-xs text-muted-foreground mb-1">Usuario DB</label>
                                            <input
                                                type="text"
                                                value={dbUser}
                                                onChange={(e) => setDbUser(e.target.value)}
                                                className="w-full px-3 py-1.5 bg-background border border-input rounded-lg focus:ring-1 focus:ring-primary outline-none text-sm"
                                                placeholder="jigsaw"
                                            />
                                        </div>
                                        <div>
                                            <label className="block text-xs text-muted-foreground mb-1">Pass DB</label>
                                            <input
                                                type="text"
                                                value={dbPassword}
                                                onChange={(e) => setDbPassword(e.target.value)}
                                                className="w-full px-3 py-1.5 bg-background border border-input rounded-lg focus:ring-1 focus:ring-primary outline-none text-foreground text-sm font-mono"
                                                placeholder="••••••"
                                            />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                            <div>
                                <label className="block text-sm font-medium text-foreground mb-1.5">Descripción</label>
                                <textarea
                                    value={description}
                                    onChange={(e) => setDescription(e.target.value)}
                                    className="w-full px-4 py-2 bg-muted/30 border border-input rounded-xl focus:ring-2 focus:ring-primary outline-none text-foreground h-28 transition-all"
                                    placeholder="Descripción general del servidor..."
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-foreground mb-1.5">Notas</label>
                                <textarea
                                    value={notes}
                                    onChange={(e) => setNotes(e.target.value)}
                                    className="w-full px-4 py-2 bg-muted/30 border border-input rounded-xl focus:ring-2 focus:ring-primary outline-none text-foreground h-28 transition-all font-mono text-xs"
                                    placeholder="Notas de mantenimiento, advertencias, etc..."
                                />
                            </div>
                        </div>
                    </form>
                </div>

                <div className="p-6 border-t border-border bg-card/50 flex justify-between items-center rounded-b-2xl shrink-0">
                    {initialData ? (
                        <button
                            type="button"
                            className="text-red-500 hover:text-red-600 text-sm font-medium opacity-80 hover:opacity-100 transition-opacity flex items-center gap-2 hover:bg-red-50 p-2 rounded-lg"
                            onClick={handleDelete}
                        >
                            Eliminar Servidor
                        </button>
                    ) : <div></div>}

                    <div className="flex gap-3">
                        <button
                            type="button"
                            onClick={onClose}
                            className="px-4 py-2 text-muted-foreground hover:text-foreground font-medium transition-colors hover:bg-muted rounded-xl"
                        >
                            Cancelar
                        </button>
                        <button
                            type="submit"
                            form="server-form"
                            disabled={loading}
                            className="px-6 py-2 bg-primary hover:bg-primary/90 text-primary-foreground font-semibold rounded-xl shadow-lg shadow-primary/20 transition-all flex items-center gap-2"
                        >
                            {loading && <Loader2 className="w-4 h-4 animate-spin" />}
                            {initialData ? 'Guardar Cambios' : 'Crear Servidor'}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ServerModal;
